import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import fs from 'node:fs';
import path from 'node:path';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

function syncToInstalledPlugin() {
	const targetDir = path.resolve('../betternotebooks');
	if (fs.existsSync(targetDir)) {
		try {
			if (fs.existsSync('main.js')) fs.copyFileSync('main.js', path.join(targetDir, 'main.js'));
			if (fs.existsSync('manifest.json')) fs.copyFileSync('manifest.json', path.join(targetDir, 'manifest.json'));
			if (fs.existsSync('styles.css')) fs.copyFileSync('styles.css', path.join(targetDir, 'styles.css'));
		} catch {
			// ignore sync error
		}
	}
}

const syncPlugin = {
	name: 'sync-plugin',
	setup(build) {
		build.onEnd(() => {
			syncToInstalledPlugin();
		});
	},
};

const prod = process.argv[2] === 'production';

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
	plugins: [syncPlugin],
});

if (prod) {
	await context.rebuild();
	syncToInstalledPlugin();
	process.exit(0);
} else {
	await context.watch();
}
